/** @jsxImportSource react */

import './global.css'
import { Provider } from 'app/provider/index.web'
import StyledJsxRegistry from './styles-provider'
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: 'WhatSupps',
  description: 'Generated by create Solito app',
  icons: {
    icon: './favicon.ico',
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <StyledJsxRegistry>
          <Provider mode="light">{children}</Provider>
        </StyledJsxRegistry>
      </body>
    </html>
  )
}
